# Generated by Django 5.2.7 on 2025-10-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertyimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='bathroooms',
            new_name='bathrooms',
        ),
    ]
